version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.15

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout
            # Download and cache dependencies
      # - restore_cache:
      #     keys:
      #       - v1-dependencies-{{ checksum "package.json" }}
      #       - v1-dependencies-
      - run:
          name: Install Dependencies
          command: npm install
      # - save_cache:
      #     key: v1-npm-deps-{{ checksum "package-lock.json" }}
      #     paths:
      #       - ./node_modules
      - run:
          name: Build
          command: npm run build
      - run:
          name: Deploy Master to Firebase
          command: ./node_modules/.bin/firebase deploy --token "$FIREBASE_DEPLOY_TOKEN" --only hosting

          # command: firebase deploy --token=$FIREBASE_DEPLOY_TOKEN