version: 2
jobs:
      build_job:
        docker:
            # specify the version you desire here
            - image: circleci/node:10.15

            # Specify service dependencies here if necessary
            # CircleCI maintains a library of pre-built images
            # documented at https://circleci.com/docs/2.0/circleci-images/
            # - image: circleci/mongo:3.4.4

        working_directory: ~/repo

        steps:
            - checkout
                    # Download and cache dependencies
            # - restore_cache:
            #     keys:
            #       - v1-dependencies-{{ checksum "package.json" }}
            #       - v1-dependencies-
            - run:
                name: Install Dependencies
                command: npm install
            # - save_cache:
            #     key: v1-npm-deps-{{ checksum "package-lock.json" }}
            #     paths:
            #       - ./node_modules
            - run:
                name: Build
                command: npm run build

            # command: firebase deploy --token=$FIREBASE_DEPLOY_TOKEN
      firebase_deploy_job:
        docker:
            # specify the version you desire here
            - image: circleci/node:10.15

            # Specify service dependencies here if necessary
            # CircleCI maintains a library of pre-built images
            # documented at https://circleci.com/docs/2.0/circleci-images/
            # - image: circleci/mongo:3.4.4

        working_directory: ~/repo
        steps:
            - run:
                name: Deploy Master to Firebase
                command: ./node_modules/.bin/firebase deploy --token "$FIREBASE_DEPLOY_TOKEN" --only hosting
workflows:
      version: 2
    firebase_deploy_master:
        triggers:
        jobs:
            - build_job
            - firebase_deploy_job:
                requires:
                    - build_job
                filters:
                    tags:
                        only: /.*/
                    branches:
                        only: master

